# Tutorial Worksheet 4

## Logical Values and Operations

The logical variables (**Boolean** variables) have only two possible values: `True` and `False`.  

In [ ]:
C1 = False

In [ ]:
C2 = True

These `True` and `False` values have corresponding numerical values of 1 and 0, respectively.  So 0 can be considered equal to `False` and 1 to `True`. `==` is one of **Relational Operators** introduced in the next section. So what logical values do C3 and C4 have?

In [ ]:
C3 = 0 == False

In [ ]:
C4 = 1 == False

Logical values can be returned by both **relational operators** and **logical operators**.

### Relational Operators

Relational operators compare operands quantitatively, using operators like ‘less than’ and ‘not equal to’. There are some relational operators listed below. 

* `>` Greater than 
* `<` Less than
* `>=` Greater than or equal to
* `<=` Less than or equal to
* `==` Equal to 
* `!=` Not equal to 

For example, variable E1 below shows whether the number n is larger than 3, and variable E2 shows if the number is smaller than 8.

In [ ]:
n = 5
E1 = n > 3
E2 = n < 8

You can also extend this to **NumPy** arrays, for example, variable E3 below shows whether the numbers in vector variable D are larger than 3, and variable E4 shows if the numbers in D are smaller than 8. Are the E3 and E4 arrays the same size as D? 

In [ ]:
import numpy as np
D = np.array([6, 2, 7, 4, 3, 8, 1])
E3 = D > 3
E4 = D < 8

Note: unlike `NumPy` arrays which are designed for maths, basic Python `list`, `dict` and `tuple` objects don't support relational operations.

### Logical Operators

Logical operators are used to assess if a statement is `True` or `False`. There are three main logical operators. 

* `and`	Logical AND (If both the operands are true then condition becomes true)
* `or` 	Logical OR  (If any of the two operands are true then condition becomes true)
* `not` Logical NOT  (Used to reverse the logical state of the operand)

Logical operators can be used to combine some relational or logical expressions. You may use some pairs of parentheses to help indicate operator precedence even though they are unnecessary for the examples below due to the fact that relational operators have higher precedence than logical operators.

In [ ]:
F1 = (4 < 2) and (7 > 3) 
F2 = (3 > 2) or (5 < 9) 
F3 = not(5 == 5)
F4 = (not 3 != 5) or (2 > 6)

Some logical operations in **NumPy**:

In [ ]:
G1 = np.array([1, 0, 1, 1, 0], dtype=bool)
G2 = np.array([0, 1, 0, 1, 0], dtype=bool)
G3 = np.logical_or(G1, G2)
G4 = np.logical_and(G1, G2)

### Question 1.

Assume that a = 15; b = -3; c = 0; d = 2 and evaluate the following expressions.
1. a > b;	
2. b > d;	
3. (a > b) and (c >= d);	
4. a == b;	
5. b != d

### Membership Operators

Python’s membership operators test for membership in a sequence, such as strings, lists, or tuples. There are two membership operators - `in`, and `not in`. `in` evaluates to `True` if it finds a variable in the specified sequence and `False` otherwise. For example, `x in y`, `in` here results in a `True` if x is a member of sequence y. `not in` evaluates to `True` if it does not find a variable in the specified sequence and `False` otherwise. For instance, `x not in y`, `not in` here results in a `True` if x is not a member of sequence y.

In [ ]:
H1 = [1, 2, 3, 4, 5, 6]
H2 = np.array([1, 2, 3, 4, 5])
H3 = 3 not in H1
H4 =  2 in H2

### Identity Operators

Python's identity operators compare the memory locations of two objects. There are two identity operators − `is`, and `is not`. `is` evaluates to `True` if the variables on either side of the operator point to the same object and `False` otherwise. For instance, `x is y`, `is` here results in `True` if `id(x)` is equal to `id(y)`. Use `help(id)` to find out what this function does. `is not` evaluates to `False` if the variables on either side of the operator point to the same object and `True` otherwise. For example, `x is not y`, `is not` here results in `True` if `id(x)` is not equal to `id(y)`.

In [ ]:
J1 = (1, 2, 3, 4, 5, 6)
J2 = (1, 2, 3, 4, 5, 6)
J3 = J1
J4 = J1 is J2
J5 = J1 is not J2
J6 = J1 is J3

Run the code cell below to compare `is` and `==` operators.

In [ ]:
J7 = [1, 2, 3, 4]
J8 = [1, 2, 3, 4]

J9 = J7==J8
J10 = J7 is J8

### Operation Precedence

Some Python operators are listed below with the precedence from highest to lowest.

* Exponentiation 
* Multiplication and division
* Addition and subtraction
* Relational operators
* Identity operators
* Membership operators
* Logical operators

Based on the list above, you are able to confirm that there is no need to use two pairs of parentheses for the previous example `F1 = (4 < 2) and (7 > 3)`. But using them can improve the readability.


## Logical Indexing

Logical indices (Boolean arrays) can often be used in a similar way to subscript indices to select out particular items from a **NumPy** array.

In [ ]:
K1 = np.arange(20)
print(K1)
k2 = (K1 % 3 == 0)  # produce a logical array as logical indices
k3 = K1[k2]  # or, K1[K1%3==0], extract a sub-array with the logical indices
K1[K1 % 3 == 0] = -1  # assign a new value to a sub-array

Note that logical indexing creates copies **not** views.

### Question 2. 

Create a 4 by 20 array whose rows are the numbers 1 to 20. Then multiply columns 0, 5, 10, 15 by 2 using Logical Indexing.

The created array should look like the one below:

```
[[ 2  2  3  4  5 12  7  8  9 10 22 12 13 14 15 32 17 18 19 20]
 [ 2  2  3  4  5 12  7  8  9 10 22 12 13 14 15 32 17 18 19 20]
 [ 2  2  3  4  5 12  7  8  9 10 22 12 13 14 15 32 17 18 19 20]
 [ 2  2  3  4  5 12  7  8  9 10 22 12 13 14 15 32 17 18 19 20]]
```

The example below demonstrates how to find, within an array, the index and value of a specific element that is the first instance of a possible group of elements satisfying a certain condition. Here, we are looking for the first integer that is equal to or greater than 80 within an array of 20 integers between 1 and 100.

In [ ]:
np.random.seed(4)
K1 = np.random.randint(1, 100, 20) # produce 20 random integers between 1 and 100
K2 = K1 >= 80 # generate a logical array  
K3 = np.argwhere(K2==True) # find the indices for 'true' array elements
K4 = K3[0] # get the index of the first element that we are looking for
K5 = K1[K4] # get the first element itself

Note: you don't need to know what `np.random.seed` does, but if you're curious then look it up in the **NumPy Documentation**, you find links to the `numpy.random.RandomState` function.

### Question 3. 

In the circuit shown in the Figure below, a resistor $R$ and a capacitor $C$ are connected in series to a battery of voltage $V$. When the switch closes, the capacitor starts to charge, and the current is a function of time $t$ as

$$ i=\frac{V}{R}e^{-\frac{t}{RC}}$$

Let VR and VC denote the voltages cross $R$ and $C$ (VR and VC are also functions of $t$), respectively. Assuming $V$ = 12 Volts, $R$ = 1 $k\Omega$, $C$ = 50 $\mu F$, and $t$ varies from 0 to 0.3 s with a step of 0.01 s, write a script and use the time array to express the current array (based on the equation above), and the corresponding VR and VC. Use relational operator to compute and find how long it takes (from which item of the time vector variable) for VC to increase to 50% of the battery voltage $V$. 

![the RC circuit](Worksheet_04_circuit.png)

Answer: 0.04 s

##  ‘if’ statement

A script can run a sequence of statements in the order they appear, but to make scripts more useful, we need to be able to tell the script to conditionally execute statements. 

`if` is the basic control element to let a script make a decision. The decision is based on a logical value as a result of an expression evaluated. The general form of an `if` statement is

```
if expression:
         statements
elif expression:
         statements
else:
         statements
```

Note that the first testing line begins with `if`, the second with `elif` meaning 'else if', and the third with `else`. Each of these is followed by a **colon** with the correspondent statements to execute. Items after the colon are indented. `if` statements can include one `else`, and as many `elif` as necessary. However, both `elif` and `else` are optional. Also note that all of the statements that are grouped together after a colon must be indented by the same amount.

If an expression is `True` or evaluated to be the number **one** (because the number **zero** is interpreted as `False`, while the number **one** is treated as `True`), the next statement will execute. For example, the function $y=e^x, \; x<0$ can be scripted using a ‘single’ `if`. Note that `if` can only evaluate ONE thing so don’t try to use a vector or array as the input.

In [ ]:
x = -2
if x < 0:
    y = np.exp(x)
    print(y)

In addition, empty lists and other objects return `False`, whereas non-empty ones are considered `True`.

An `if` statement can also include an `elif`, which executes if the first part is `False` or equal to zero. For example,

$$ y = \begin{cases} e^x, & \mbox{if } x<0 \\ \sqrt{x}, & \mbox{if } x\geq 0 \end{cases} $$

In [ ]:
x = 4
if x < 0:
    y = np.exp(x)
    print(y)
elif x >= 0:
    y = np.sqrt(x)
    print(y)

In addition to having any number of `elif` clauses, an `if` construct can also include one `else` clause. For example, 

$$ y = \begin{cases} e^x, & \mbox{if } x<0 \\ \sqrt{x}, & \mbox{if } 0\leq x<5\\ \ln x, & \mbox{if } x\geq 5 \end{cases} $$

In [ ]:
x = 6
if x < 0:
    y = np.exp(x)
    print(y)
elif x < 5:
    y = np.sqrt(x)
    print(y)
else:
    y = np.log(x)
    print(y)

Compare these three examples above with the general form of the `if` statement to confirm which parts of the general form are optional.

`if` statements can be nested using indentation. For example, the above code can be rewritten using nested `if` statements below.

In [ ]:
x = 6
if x < 0:
    y = np.exp(x)
    print(y)
else:
    if x < 5:
        y = np.sqrt(x)
        print(y)
    else:
        y = np.log(x)
        print(y)

Note: when using many `elif` statements to make decisions, make sure to cover all possible cases, a common mistake is to take one action if `x > y` make another action if `x < y` and miss out the option where `x == y`.

### Question 4.

Write a script to evaluate the value of the following function and test your script for point $(x, y) = (-2, -3)$.

$$ f(x,y) = \begin{cases} x+y, & \mbox{if } x\geq0 \mbox{ and } y\geq0 \\ x+y^2, & \mbox{if } x\geq0 \mbox{ and } y<0 \\ x^2+y, & \mbox{if } x<0 \mbox{ and } y\geq0 \\ x^2+y^2, & \mbox{if } x<0 \mbox{ and } y<0 \end{cases} $$


